apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io #if deleted, deletes entire stack, i.e. not just the app
spec:
  destination:
    namespace: guestbook
    # name: dev-cluster
    name: in-cluster
  project: default
  source:
    path: argocd/projects/dev/guestbook
    repoURL: https://github.com/JustasBud/kubernetes
    targetRevision: HEAD
