apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applebananaingressrules
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io #if deleted, deletes entire stack, i.e. not just the app
spec:
  destination:
    namespace: applebanana #has to be deployed in the same namespace as the exposed app
    # name: dev-cluster
    name: in-cluster
  project: default
  source:
    path: argocd/projects/dev/nginxTestApps/ingress
    repoURL: https://github.com/JustasBud/kubernetes
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
